### ISSUE TITLE
Selection icons glitch

### ISSUE THREAD

**Issue by speedlimits65** [josharenson/GTFOklahoma#15]
in ths first run-through, the selection icons (little circles up top) corresponded to the number of selections. when i hit back to start a new game*, the number of circles increased, and the items repeated. items repeated more and more as i kept starting a new game.

*back should go back to the previous menu, not the new game screen

**Comment by josharenson** [comment]
I fixed the first issue you mention. As for "*back should go back to the previous menu, not the new game screen" its filed under #13 already.
